baseURL = "https://themoralpanda.github.io/"
languageCode = "en-us"
title = "Vig Venkat"
theme = "elephants"
publishDir = "docs"
staticDir = "static"
[params]
    sitename = "Vig Venkat"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true